services:
  app:
    container_name: "{{cookiecutter.__package_slug.replace('_', '-')}}"
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./data:/app/data